name: Laravel

on:
  push:
  pull_request:

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: laravel
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      redis:
        image: redis:5.0
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    steps:
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - uses: actions/checkout@v2
      name: Checkout private tools
      with:
        repository: laravel/nova
        token: ${{ secrets.MY_GITHUB_TOKEN }}
        path: nova
        ref: "3.0"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Prepare storage
      run: php artisan storage:link
    - name: Upgrade Chrome Driver
      run: vendor/bin/dusk-updater detect --auto-update
    - name: Start Chrome Driver
      run: vendor/laravel/dusk/bin/chromedriver-linux &
    - name: Sleep for 5 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '5s'
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit --exclude-group=external-network --exclude-group=local-time
      env:
        DB_PORT: ${{ job.services.mysql.ports[3306] }}
        DB_USERNAME: root
    - name: Upload Failed Screenshots
      uses: actions/upload-artifact@v2-preview
      if: failure()
      with:
        name: screenshots
        path: tests/Browser/screenshots/*
